# Generated by Django 5.2.5 on 2025-08-21 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='⭐', max_length=10)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hedef Kategorisi',
                'verbose_name_plural': 'Hedef Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hedef Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('category', models.CharField(choices=[('house', '🏠 Ev Almak'), ('car', '🚗 Araç Almak'), ('vacation', '🌴 Tatil/Seyahat'), ('wedding', '💍 Düğün'), ('education', '🎓 Eğitim'), ('emergency', '🚨 Acil Durum Fonu'), ('retirement', '💰 Emeklilik'), ('health', '🏥 Sağlık'), ('investment', '💼 Yatırım'), ('custom', '⭐ Özel Hedef')], max_length=20, verbose_name='Kategori')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hedef Tutar')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mevcut Tutar')),
                ('target_date', models.DateField(verbose_name='Hedef Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aylık Katkı')),
                ('priority', models.IntegerField(choices=[(1, 'Yüksek'), (2, 'Orta'), (3, 'Düşük')], default=2, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('paused', 'Durduruldu'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_contribute', models.BooleanField(default=False, verbose_name='Otomatik Katkı')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='Bildirimler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finansal Hedef',
                'verbose_name_plural': 'Finansal Hedefler',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Katkı Tutarı')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Otomatik'), ('bonus', 'İkramiye/Bonus'), ('salary', 'Maaş Kesintisi'), ('transfer', 'Transfer')], default='manual', max_length=20, verbose_name='Kaynak')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrarlanan')),
                ('next_contribution_date', models.DateField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goal_tracker.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef Katkısı',
                'verbose_name_plural': 'Hedef Katkıları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GoalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('contribution', 'Katkı Hatırlatması'), ('deadline', 'Deadline Hatırlatması'), ('milestone', 'Milestone Hatırlatması'), ('review', 'Gözden Geçirme')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('once', 'Tek Seferlik')], default='monthly', max_length=20)),
                ('next_reminder_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='goal_tracker.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef Hatırlatması',
                'verbose_name_plural': 'Hedef Hatırlatmaları',
                'ordering': ['next_reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('target_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Hedef Yüzdesi')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Hedef Tutar')),
                ('achieved_date', models.DateTimeField(blank=True, null=True, verbose_name='Başarıldığı Tarih')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Başarıldı')),
                ('reward_text', models.CharField(blank=True, max_length=200, verbose_name='Ödül Metni')),
                ('celebration_message', models.TextField(blank=True, verbose_name='Kutlama Mesajı')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goal_tracker.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef Kilometre Taşı',
                'verbose_name_plural': 'Hedef Kilometre Taşları',
                'ordering': ['target_percentage'],
                'unique_together': {('goal', 'target_percentage')},
            },
        ),
    ]
