# Generated by Django 5.2.5 on 2025-08-20 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', '🍽️ Gıda & İçecek'), ('transport', '🚗 Ulaşım'), ('entertainment', '🎬 Eğlence'), ('bills', '💡 Faturalar'), ('shopping', '🛍️ Alışveriş'), ('health', '🏥 Sağlık'), ('education', '📚 Eğitim'), ('investment', '📈 Yatırım'), ('housing', '🏠 Konut'), ('other', '📦 Diğer')], max_length=20, unique=True)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('budget_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Harcama Kategorisi',
                'verbose_name_plural': 'Harcama Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('expense_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_necessary', models.BooleanField(default=True, help_text='AI tarafından belirlenen gereklilik')),
                ('ai_category_confidence', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensecategory')),
            ],
            options={
                'verbose_name': 'Harcama',
                'verbose_name_plural': 'Harcamalar',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('warning', '⚠️ Uyarı'), ('suggestion', '💡 Öneri'), ('achievement', '🎉 Başarı'), ('trend', '📊 Trend')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harcama İçgörüsü',
                'verbose_name_plural': 'Harcama İçgörüleri',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expensecategory')),
            ],
            options={
                'verbose_name': 'Bütçe',
                'verbose_name_plural': 'Bütçeler',
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
