# Generated by Django 5.2.5 on 2025-08-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField()),
                ('avg_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category_analysis', models.JSONField()),
                ('top_categories', models.JSONField()),
                ('insights', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kredi Kartı Ekstresi',
                'verbose_name_plural': 'Kredi Kartı Ekstreleri',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='StatementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('ai_tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expense_tracker.creditcardstatement')),
            ],
            options={
                'verbose_name': 'Ekstre İşlemi',
                'verbose_name_plural': 'Ekstre İşlemleri',
                'ordering': ['-date'],
            },
        ),
    ]
