# Generated by Django 5.2.5 on 2025-08-20 16:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HOUSING', 'Ev/Konut'), ('VEHICLE', 'Araç'), ('TRAVEL', 'Seyahat/Tatil'), ('EDUCATION', 'Eğitim'), ('RETIREMENT', 'Emeklilik'), ('EMERGENCY', 'Acil Durum Fonu'), ('INVESTMENT', 'Yatırım'), ('DEBT_PAYOFF', 'Borç Ödeme'), ('BUSINESS', 'İş/Girişim'), ('OTHER', 'Diğer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('color', models.CharField(default='#10B981', max_length=7)),
            ],
            options={
                'verbose_name': 'Hedef Kategorisi',
                'verbose_name_plural': 'Hedef Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('target_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PAUSED', 'Duraklatılmış'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='ACTIVE', max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('feasibility_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recommended_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_analysis', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_goals.goalcategory')),
            ],
            options={
                'verbose_name': 'Finansal Hedef',
                'verbose_name_plural': 'Finansal Hedefler',
                'ordering': ['-priority', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='financial_goals.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef Aşaması',
                'verbose_name_plural': 'Hedef Aşamaları',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('TIMELINE', 'Zaman Çizelgesi'), ('AMOUNT', 'Miktar Ayarı'), ('STRATEGY', 'Strateji Değişikliği'), ('PRIORITY', 'Öncelik Sıralaması'), ('RISK', 'Risk Uyarısı'), ('OPPORTUNITY', 'Fırsat Bildirimi')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='financial_goals.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef Önerisi',
                'verbose_name_plural': 'Hedef Önerileri',
                'ordering': ['-confidence_score', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Para Yatırma'), ('WITHDRAWAL', 'Para Çekme'), ('INTEREST', 'Faiz Getirisi'), ('BONUS', 'Bonus/İkramiye'), ('TRANSFER', 'Transfer')], max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial_goals.financialgoal')),
            ],
            options={
                'verbose_name': 'Hedef İşlemi',
                'verbose_name_plural': 'Hedef İşlemleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SavingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('PERCENTAGE', 'Gelir Yüzdesi'), ('FIXED_AMOUNT', 'Sabit Miktar'), ('ROUND_UP', 'Yuvarla ve Biriktir'), ('ENVELOPE', 'Zarf Yöntemi'), ('AUTOMATIC', 'Otomatik Transfer'), ('MILESTONE', 'Aşamalı Tasarruf')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_of_income', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='financial_goals.financialgoal')),
            ],
            options={
                'verbose_name': 'Tasarruf Stratejisi',
                'verbose_name_plural': 'Tasarruf Stratejileri',
            },
        ),
    ]
