# Generated by Django 5.2.5 on 2025-08-20 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('market', models.CharField(choices=[('BIST', 'Borsa İstanbul'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange'), ('CRYPTO', 'Cryptocurrency'), ('FOREX', 'Foreign Exchange')], max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='TRY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('STRONG_BUY', 'Güçlü Al'), ('BUY', 'Al'), ('HOLD', 'Tut'), ('SELL', 'Sat'), ('STRONG_SELL', 'Güçlü Sat')], max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Düşük Risk'), ('MEDIUM', 'Orta Risk'), ('HIGH', 'Yüksek Risk'), ('VERY_HIGH', 'Çok Yüksek Risk')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd_signal', models.CharField(blank=True, max_length=10)),
                ('moving_avg_20', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moving_avg_50', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('analysis_text', models.TextField()),
                ('key_factors', models.JSONField(default=list)),
                ('news_sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='stock_market.stocksymbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_stocks', models.ManyToManyField(blank=True, to='stock_market.stocksymbol')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.CharField(choices=[('CONSERVATIVE', 'Muhafazakar'), ('MODERATE', 'Orta Riskli'), ('AGGRESSIVE', 'Agresif'), ('VERY_AGGRESSIVE', 'Çok Agresif')], max_length=20)),
                ('investment_goal', models.CharField(choices=[('CAPITAL_PRESERVATION', 'Sermaye Korunması'), ('INCOME_GENERATION', 'Gelir Üretimi'), ('BALANCED_GROWTH', 'Dengeli Büyüme'), ('AGGRESSIVE_GROWTH', 'Agresif Büyüme'), ('SPECULATION', 'Spekülatif Yatırım')], max_length=30)),
                ('investment_horizon', models.IntegerField()),
                ('monthly_investment_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('experience_years', models.IntegerField(default=0)),
                ('previously_invested_instruments', models.JSONField(default=list)),
                ('preferred_sectors', models.JSONField(default=list)),
                ('avoided_sectors', models.JSONField(default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('quiz_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('change_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stock_market.stocksymbol')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market.stocksymbol')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stock_market.userportfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'stock')},
            },
        ),
    ]
