# Generated by Django 5.2.5 on 2025-08-20 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Kullanıcı'), ('bot', 'Bot')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Metin'), ('analysis', 'Analiz'), ('recommendation', 'Tavsiye')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.aiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_debts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('credit_worthiness_score', models.IntegerField()),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommended_loan_term', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], max_length=20)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('ai_recommendations', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
